#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'one-team-ex-stuck','console_scripts','ex_controller_test'
__requires__ = 'one-team-ex-stuck'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('one-team-ex-stuck', 'console_scripts', 'ex_controller_test')()
    )
