#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'multi-du-udpcomm-01-pkg','console_scripts','du_controller_014'
__requires__ = 'multi-du-udpcomm-01-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('multi-du-udpcomm-01-pkg', 'console_scripts', 'du_controller_014')()
    )
