#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'two-team-ex-cnp','console_scripts','ex_controller_005'
__requires__ = 'two-team-ex-cnp'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('two-team-ex-cnp', 'console_scripts', 'ex_controller_005')()
    )
