coope_controler:
  ros__parameters:
    param_turtlePublish_controller: 'du_014/cmd_vel'
    param_turtleSubsc_controller: 'du_014/pose'
    param_turtlePublish_communication: 'du_014/pose'
    param_turtleSubsc_communication: 'du_014/cmd_vel'
    param_timer_period: '0.1'

