#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'two-team-du-stuck','console_scripts','du_controller_016'
__requires__ = 'two-team-du-stuck'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('two-team-du-stuck', 'console_scripts', 'du_controller_016')()
    )
