#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'one-team-du-stuck','console_scripts','du_controller_017'
__requires__ = 'one-team-du-stuck'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('one-team-du-stuck', 'console_scripts', 'du_controller_017')()
    )
