#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'four-team-du-cnp','console_scripts','du_communication_025'
__requires__ = 'four-team-du-cnp'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('four-team-du-cnp', 'console_scripts', 'du_communication_025')()
    )
