#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'testplay','console_scripts','du_communication_012'
__requires__ = 'testplay'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('testplay', 'console_scripts', 'du_communication_012')()
    )
