#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'six-team-du-stuck','console_scripts','du_communication_023'
__requires__ = 'six-team-du-stuck'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('six-team-du-stuck', 'console_scripts', 'du_communication_023')()
    )
