#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'one-team-ex-base-master','console_scripts','ex_controller_000'
__requires__ = 'one-team-ex-base-master'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('one-team-ex-base-master', 'console_scripts', 'ex_controller_000')()
    )
